---
title: "Networks Assignment 2"
description: |
  Intro Assignment for DACSS 697E course 'Social and Political Network Analysis'
categories:
  - networks
  - homework
author:
  - name: Kristina Becvar
    url: https://www.kristinabecvar.com
slug: kbec2022networks1
date: 02-04-2022
base_url: https://www.kristinabecvar.com
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Social network analysis (SNA) is the process of investigating social structures through the use of networks and graph theory. It characterizes networked structures in terms of nodes (individual actors, people, or things within the network) and the ties, edges, or links (relationships or interactions) that connect them. Examples of social structures commonly visualized through social network analysis include social media networks, memes spread, information circulation, friendship and acquaintance networks, business networks, knowledge networks, difficult working relationships, social networks, collaboration graphs, kinship, disease transmission, and sexual relationships. These networks are often visualized through sociograms in which nodes are represented as points and ties are represented as lines. These visualizations provide a means of qualitatively assessing networks by varying the visual representation of their nodes and edges to reflect attributes of interest.

Social network analysis has emerged as a key technique in modern sociology. It has also gained significant popularity in anthropology, biology, demography, communication studies, economics, geography, history, information science, organizational studies, political science, public health, social psychology, development studies, sociolinguistics, and computer science, and is now commonly available as a consumer tool.
